package exceptionhandlingdiscussion;

public class Test2 {
	
	public static void main(String[] args) {
		
		int i=10;
		int j=20;
		
		if(i>5)
		{
			throw new ArithmeticException("morning batch exception handling");
		}
		if(j>20)
		{
			
		}
		System.out.println("no exeption caused during the progrm");
		
	}

}
